version: '3.1'

services:
  openweatherservice:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"

    depends_on:
      - mongo
      - mongo-express
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /usr/share/mongodb/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
